### ISSUE TITLE
Inconsistency between the UKLEX L2 labels number shown in README.md and paper

### ISSUE THREAD

**Issue by simonucl** [coastalcph/Multi-Label-Classification-T5#2]
Hello Author,

Thanks for gathering all four of the datasets. When I was comparing the paper and the repository, I found that in Table 1 of the original paper, the |L2| for the UKLEX dataset is 69; however, in the README and the dataset provided, there are only 40 unique labels for the same dataset. Could the author provide some clarification on this inconsistency, as it hinders the progress of constructing the hierarchy by linking the L1 and L2 labels?

Thanks in advance!

Best,
Simon

**Comment by iliaschalkidis** [comment]
Hi @simonucl,

It's clearly a typo, the labels are presented here: https://github.com/coastalcph/Multi-Label-Classification-T5/blob/4741edcf4e86fa6023ce125f24dd0bb3a8ebfd2f/data/multilabel_bench/label_descriptors.py#L559C31-L598C43

It's coming from a reorganization of the labels used in prior work. I'll update the manuscript.
